import numpy as np
import pandas as pd
import os.path

######### Для выгрузки 1 пользователя ######### ниже для предикт
name_folder_chat='\\recomendation_profile\\'
login_name='pvmek@mail.ru'
password_name ='Qwertyuiop15'

likes_f=os.path.abspath(os.curdir)+name_folder_chat+'required_files\\likes_total.csv'
group_type_group_f='required_files/groups_type_groups.csv'

top_groups=['1poetry', 'bon', 'borsch', 'dayvinchik', 'dfilm',
       'evil_incorparate', 'exclusive_muzic', 'fuck_humor', 'ifun',
       'iwantyou', 'kino_kaif', 'kino_mania', 'kinomania', 'kudago',
       'leprum', 'mosc1', 'mudakoff', 'overhear', 'pn6', 'rapnewrap',
       'ru.esquire', 'sci', 'science_technology', 'vinevinevine', 'xfilm']

path_to_save=os.path.abspath(os.curdir)+'\\Data\\recomendations'


top_type_groups=['Автомобили',
 'Бизнес',
 'Городское сообщество',
 'Закрытая группа',
 'Здоровый образ жизни',
 'Игры',
 'Интернет-СМИ',
 'Кино',
 'Кулинария, рецепты',
 'Культура',
 'Литература',
 'Молодёжное движение',
 'Музыка',
 'Музыкант',
 'Наука',
 'Образование',
 'Общество',
 'Объявления',
 'Открытая группа',
 'Отношения полов',
 'Публичная страница',
 'Стиль, одежда, обувь',
 'Творчество',
 'Туризм, путешествия',
 'Уход за собой',
 'Философия',
 'Фотография',
 'Футбол',
 'Шоу, передача',
 'Юмор']

features={'id':['yes','int'],
'first_name':['no','str'],
'last_name':['no','str'],
'deactivated':['yes','str'],
'is_closed':['no','bool'],
'can_access_closed':['no','bool'],
'about':['yes','str'],
'activities':['yes','str'],
'bdate':['no','str'],
'blacklisted':['no','bool'],
'blacklisted_by_me':['no','bool'],
'books':['yes','str'],
'can_post':['yes','bool'],
'can_see_all_posts':['yes','bool'],
'can_see_audio':['no','bool'],
'can_send_friend_request':['yes','bool'],
'can_write_private_message':['yes','bool'],
'career__group_id':['no','int'],
'career__company':['no','str'],
'career__country_id':['no','int'],
'career__city_id':['no','int'],
'career__city_name':['no','str'],
'career__from':['no','int'],
'career__until':['no','int'],
'career__position':['no','int'],
'city__id':['yes','int'],
'city__title':['no','str'],
'common_count':['no','int'],
'skype':['yes','str'],
'facebook':['yes','str'],
'twitter':['yes','str'],
'instagram':['yes','str'],
'livejournal':['no',''],
'mobile_phone':['yes','str'],
'home_phone':['no','str'],
'counters__albums':['no','int'],
'counters__videos':['no','int'],
'counters__audios':['no','int'],
'counters__photos':['no','int'],
'counters__notes':['no','int'],
'counters__friends':['no','int'],
'counters__groups':['no','int'],
'counters__online_friends':['no','int'],
'counters__mutual_friends':['no','int'],
'counters__user_videos':['no','int'],
'counters__followers':['no','int'],
'counters__pages':['no','int'],
'country__id':['no','int'],
'country__title':['no','str'],
'domain':['yes','str'],
'education__university':['no','int'],
'education__university_name':['no','str'],
'education__faculty':['no','str'],
'education__faculty_name':['no','str'],
'education__graduation':['no','int'],
'followers_count':['yes','int'],
'friend_status':['no','int'],
'games':['yes','str'],
'has_mobile':['no','bool'],
'has_photo':['yes','bool'],
'home_town':['no','str'],
'interests':['yes','str'],
'is_favorite':['no','bool'],
'is_hidden_from_feed':['no','bool'],
'is_friend':['no','bool'],
'last_seen__time':['yes','int'],
'last_seen__platform':['yes','cat'],
'maiden_name':['no','str'],
'military__unit':['no','str'],
'military__unit_id':['no','id'],
'military__country_id':['no','int'],
'military__from':['no','int'],
'military__until':['no','int'],
'movies':['yes','str'],
'music':['yes','str'],
'nickname':['yes','str'],
'occupation__type':['yes','cat'],
'occupation__id':['yes','int'],
'occupation__name':['no','str'],
'online':['no','bool'],
'personal__political':['yes','cat'],
'personal__langs':['yes','cat'],
'personal__religion':['yes','str'],
'personal__inspired_by':['yes','str'],
'personal__people_main':['yes','cat'],
'personal__life_main':['yes','cat'],
'personal__smoking':['yes','cat'],
'personal__alcohol':['yes','cat'],
'photo_50':['no','str'],
'photo_100':['no','str'],
'photo_200_orig':['no','str'],
'photo_200':['no','str'],
'photo_400_orig':['no','str'],
'photo_id':['no','str'],
'photo_max':['no','str'],
'photo_max_orig':['no','str'],
'quotes':['yes','str'],
'relatives__id':['no','int'],
'relatives__name':['no','str'],
'relatives__type':['yes','cat'],
'relation':['yes','cat'],
'relation_partner__first_name':['no','str'],
'relation_partner__id':['yes','int'],
'relation_partner__last_name':['no','str'],
'schools__id':['no','int'],
'schools__country':['no','int'],
'schools__city':['no','int'],
'schools__name':['no','str'],
'schools__year_from':['no','int'],
'schools__year_to':['no','int'],
'schools__year_graduated':['no','int'],
'schools__class':['no','str'],
'schools__speciality':['no','str'],
'schools__type':['no','int'],
'schools__type_str':['yes','cat'],
'screen_name':['no','str'],
'sex':['yes','int'], ## поменял на int
'site':['no','str'],
'status':['yes','str'],
'timezone':['no','int'],
'trending':['no','bool'],
'tv':['yes','str'],
'universities__id':['no','int'],
'universities__country':['no','int'],
'universities__city':['no','int'],
'universities__name':['no','str'],
'universities__faculty':['no','int'],
'universities__faculty_name':['no','str'],
'universities__chair':['no','int'],
'universities__chair_name':['no','str'],
'universities__graduation':['no','int'],
'universities__education_form':['yes','cat'],
'universities__education_status':['yes','cat'],
'verified':['yes','bool'],
'wall_default':['no','cat']}
features=pd.DataFrame(features).T.reset_index()
features.columns=['All_columns','Take','Type']
features_func=['domain','mobile_phone']

columns_for_df=['about', 'activities', 'books', 'can_post', 'can_see_all_posts',
       'can_send_friend_request', 'can_write_private_message', 'domain',
       'facebook', 'followers_count', 'games', 'has_photo', 'id',
       'instagram', 'interests', 'movies', 'music', 'nickname',
       'occupation__id', 'personal__inspired_by', 'personal__langs',
       'personal__religion', 'quotes', 'relation', 'relation_partner__id',
       'sex', 'skype', 'status', 'tv', 'twitter', 'verified', 'year',
       'last_seen__platform_1.0', 'last_seen__platform_2.0',
       'last_seen__platform_3.0', 'last_seen__platform_4.0',
       'last_seen__platform_5.0', 'last_seen__platform_7.0',
       'mobile_phone_Не нормальный', 'mobile_phone_Нормальный',
       'occupation__type_school', 'occupation__type_university',
       'occupation__type_work', 'personal__alcohol_1.0',
       'personal__alcohol_2.0', 'personal__alcohol_3.0',
       'personal__alcohol_4.0', 'personal__alcohol_5.0',
       'personal__life_main_1.0', 'personal__life_main_2.0',
       'personal__life_main_3.0', 'personal__life_main_4.0',
       'personal__life_main_5.0', 'personal__life_main_6.0',
       'personal__life_main_7.0', 'personal__life_main_8.0',
       'personal__people_main_1.0', 'personal__people_main_2.0',
       'personal__people_main_3.0', 'personal__people_main_4.0',
       'personal__people_main_5.0', 'personal__people_main_6.0',
       'personal__political_1.0', 'personal__political_2.0',
       'personal__political_3.0', 'personal__political_4.0',
       'personal__political_5.0', 'personal__political_6.0',
       'personal__political_7.0', 'personal__political_8.0',
       'personal__political_9.0', 'personal__smoking_1.0',
       'personal__smoking_2.0', 'personal__smoking_3.0',
       'personal__smoking_4.0', 'personal__smoking_5.0',
       'relatives__type_child', 'relatives__type_grandchild',
       'relatives__type_grandparent', 'relatives__type_parent',
       'relatives__type_sibling', 'schools__type_str_Автошкола',
       'schools__type_str_Вечерняя школа', 'schools__type_str_Гимназия',
       'schools__type_str_Детский сад', 'schools__type_str_Колледж',
       'schools__type_str_Лицей', 'schools__type_str_Музыкальная школа',
       'schools__type_str_Спортивная школа', 'schools__type_str_Техникум',
       'schools__type_str_Училище', 'schools__type_str_Худ. школа',
       'schools__type_str_Школа', 'schools__type_str_Школа-интернат',
       'universities__education_form_Дистанционное обучение',
       'universities__education_form_Заочное отделение',
       'universities__education_form_Очно-заочное отделение',
       'universities__education_form_Очное отделение',
       'universities__education_form_Экстернат',
       'universities__education_status_Абитуриент',
       'universities__education_status_Абитуриентка',
       'universities__education_status_Адъюнкт',
       'universities__education_status_Аспирантка',
       'universities__education_status_Ассистент-стажер',
       'universities__education_status_Ассистент-стажёр',
       'universities__education_status_Выпускник (бакалавр)',
       'universities__education_status_Выпускник (магистр)',
       'universities__education_status_Выпускник (специалист)',
       'universities__education_status_Выпускница (бакалавр)',
       'universities__education_status_Выпускница (магистр)',
       'universities__education_status_Выпускница (специалист)',
       'universities__education_status_Доктор наук',
       'universities__education_status_Докторант',
       'universities__education_status_Интерн',
       'universities__education_status_Клинический ординатор',
       'universities__education_status_Соискатель',
       'universities__education_status_Соискательница',
       'universities__education_status_Студент (бакалавр)',
       'universities__education_status_Студент (магистр)',
       'universities__education_status_Студент (специалист)',
       'universities__education_status_Студентка (бакалавр)',
       'universities__education_status_Студентка (магистр)',
       'universities__education_status_Студентка (специалист)']

########## Предикт ############

model_f=os.path.abspath(os.curdir)+name_folder_chat+'required_files/lgbm_140919_2.pkl'
features_for_model_f=os.path.abspath(os.curdir)+name_folder_chat+'required_files/features_02062019.csv'

df_model_f='df_for_model_with_w2v_03_11_2018_all_men_women.tab'
df_for_predict_f=os.path.abspath(os.curdir)+name_folder_chat+'required_files/df_for_predict_women_1204.pickle'

good_names_filt_f='/home/pevvva/Filters_201901/Filter_id_names.csv'
friends_filt_f='/home/pevvva/Filters_201901/Filter_id_friends.csv'
woman_prob_in_relation_filt_f='/home/pevvva/Filters_201901/woman_probability_in_relation_16_11_18.csv'
friends_sex_f='/home/pevvva/Likes_Friends_Groups/Data_friends_sex.csv'
topNGroups_f='/home/pevvva/Likes_Friends_Groups/PIVOT_topNGroups.csv'
topNType_f='/home/pevvva/Likes_Friends_Groups/PIVOT_topNType_Groups.csv'